name: deploy 到 beta 环境

on:
  push:
    branches:
      - master

env:
  BETA_DEPLOY_SSH_PRIVATE_KEY: ${{ secrets.BETA_DEPLOY_SSH_PRIVATE_KEY }}
  BETA_DEPLOY_USER: ${{ secrets.BETA_DEPLOY_USER }}
  BETA_DEPLOY_PATH: ${{ secrets.BETA_DEPLOY_PATH }}
  BETA_DEPLOY_HOST: ${{ secrets.BETA_DEPLOY_HOST }}
  BETA_HOST_KEY: ${{ secrets.BETA_HOST_KEY }}
  # 测试的配置
  BACKEND_E2E_TEST_ALI_OSS_ACCESS_KEY_ID: ${{ secrets.BACKEND_E2E_TEST_ALI_OSS_ACCESS_KEY_ID }}
  BACKEND_E2E_TEST_ALI_OSS_ACCESS_KEY_SECRET: ${{ secrets.BACKEND_E2E_TEST_ALI_OSS_ACCESS_KEY_SECRET }}
  # 测试的配置 END
  # 存储图片的配置
  BACKEND_STORE_IMAGES_ALI_OSS_ACCESS_KEY_ID: ${{ secrets.BACKEND_STORE_IMAGES_ALI_OSS_ACCESS_KEY_ID }}
  BACKEND_STORE_IMAGES_ALI_OSS_ACCESS_KEY_SECRET: ${{ secrets.BACKEND_STORE_IMAGES_ALI_OSS_ACCESS_KEY_SECRET }}
  # 存储图片的配置 END
  # 前端资源的配置
  F2E_ASSETS_ALI_OSS_ACCESS_KEY_ID: ${{ secrets.F2E_ASSETS_ALI_OSS_ACCESS_KEY_ID }}
  F2E_ASSETS_ALI_OSS_ACCESS_KEY_SECRET: ${{ secrets.F2E_ASSETS_ALI_OSS_ACCESS_KEY_SECRET }}
  F2E_ASSETS_ALI_OSS_BUCKET: 'beta-assets-tuchuang-space'
  F2E_ASSETS_WEBPACK_PUBLIC_PATH: 'https://beta.assets.tuchuang.space'
  # 前端资源的配置 END

jobs:
  backend-test:
    env:
      CI: true
      KARMA_SINGLE_MODE: on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: 生成 self-hosted.config.js
      run: |
        node ./scripts/generateSelfHostedConfigFromEnv.js
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: install xvfb
      run: sudo apt-get install xvfb
    - name: yarn install, and test
      run: |
        cd ./backend
        yarn --version
        yarn cache clean
        yarn install
        yarn run test
  frondend-test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - uses: ./.github/actions/frondend-windows-test
  bff-test:
    env:
      CI: true
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: yarn install, and test
      run: |
        cd ./frondend
        yarn --version
        yarn cache clean
        yarn install
        yarn run test:bff
  deploy-backend-to-beta:
    needs: backend-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: copy BETA_DEPLOY_SSH_PRIVATE_KEY
      run: |
        mkdir ~/.ssh
        echo $BETA_DEPLOY_SSH_PRIVATE_KEY > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        sed -i -e "s/\\\\n/\n/g" ~/.ssh/id_rsa
    - name: copy host key
      run: |
        echo $BETA_HOST_KEY > ~/.ssh/known_hosts
    - name: deploy to beta
      run: |
        cd ./backend
        sudo npm install -g pm2
        pm2 deploy ecosystem.config.js beta
  deploy-frondend-to-beta:
    needs: [deploy-backend-to-beta, frondend-test, bff-test]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: 生成 self-hosted.config.js
      run: |
        node ./scripts/generateSelfHostedConfigFromEnv.js
    - name: copy BETA_DEPLOY_SSH_PRIVATE_KEY
      run: |
        mkdir ~/.ssh
        echo $BETA_DEPLOY_SSH_PRIVATE_KEY > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        sed -i -e "s/\\\\n/\n/g" ~/.ssh/id_rsa
    - name: copy host key
      run: |
        echo $BETA_HOST_KEY > ~/.ssh/known_hosts
    - name: deploy to beta
      run: |
        cd ./frondend
        sudo npm install -g pm2
        sudo yarn install
        sudo npx cross-env DEPLOY_TYPE=beta yarn run build:production
        npx cross-env DEPLOY_TYPE=beta node ./publish.js
        pm2 deploy ecosystem.config.js beta
